In [1]:
%matplotlib inline 
%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

In [35]:
import fgspectra.power, fgspectra.frequency, fgspectra.models

In [105]:
import fgspectra.models

freqs = [148.0, 220.0]
nu_0 = 150.0
ell_0 = 3000

tSZ1 = fgspectra.models.ThermalSZ(nu_0=nu_0, ell_0=ell_0)

# tSZ1.model( 150.0, 150.0, ell=np.array([3000]), a_tSZ=1.0)

tSZ1.get_mix(freqs=freqs, l_max=4000, a_tSZ=1.0)

# kSZ1 = fgspectra.models.KineticSZ(nu_0=nu_0, ell_0=ell_0)

# def secondaries(ell, par):
#     """returns mixing matrix """
#     return (
#         tSZ1.mix(nu, a_tSZ=par['a_tSZ'], freqs=freqs) + 
#         kSZ1.mix(nu, a_kSZ=par['a_kSZ'], freqs=freqs)
#     )

148.0 148.0 {'nu_0': 150.0, 'ell_0': 3000, 'a_tSZ': 1.0}
148.0 220.0 {'nu_0': 150.0, 'ell_0': 3000, 'a_tSZ': 1.0}
220.0 148.0 {'nu_0': 150.0, 'ell_0': 3000, 'a_tSZ': 1.0}
220.0 220.0 {'nu_0': 150.0, 'ell_0': 3000, 'a_tSZ': 1.0}


array([[[ 1.88272572e-06,  1.88272572e-06,  1.88272572e-06, ...,
          1.05900686e+00,  1.05896920e+00,  1.05893343e+00],
        [-7.49187486e-08, -7.49187486e-08, -7.49187486e-08, ...,
         -4.21407472e-02, -4.21392489e-02, -4.21378254e-02]],

       [[-7.49187486e-08, -7.49187486e-08, -7.49187486e-08, ...,
         -4.21407472e-02, -4.21392489e-02, -4.21378254e-02],
        [ 2.98121965e-09,  2.98121965e-09,  2.98121965e-09, ...,
          1.67689431e-03,  1.67683469e-03,  1.67677805e-03]]])

In [14]:
# tsz_frq = fgspectra.frequency.tSZ1()

In [21]:
tsz_ell = fgspectra.power.sz_x_cib_template()

In [24]:
tsz_ell.powspec(5)

0.0001065846

In [42]:
import os

packagedir = list(fgspectra.__path__)[0]
dirname = os.path.join( os.path.dirname(packagedir), 'data') 


In [43]:
dirname

'/home/zequnl/Projects/fgspectra/data'

In [29]:
def testfunc(**kwargs):
    print(kwargs)
    print( 'aTSZ' in kwargs )
    
testfunc(**{'aTSZ':1})

{'aTSZ': 1}
True


In [30]:
for i in {'aTSZ':1}:
    print(i)

aTSZ


In [51]:
import numpy as np
a, b = np.array( [[1,2], [3,4]])

In [49]:
np.array( [[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [47]:
a, b

(array([1, 2]), array([3, 4]))

In [50]:
len(a)

2